# Generated by Django 3.0.3 on 2021-07-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210718_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.Customer'),
        ),
    ]
