# Generated by Django 3.0.3 on 2021-07-18 18:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20210719_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_mood', multiselectfield.db.fields.MultiSelectField(choices=[('happy', 'HAPPY'), ('sad', 'SAD'), ('anxious', 'ANXIOUS'), ('calm', 'CALM'), ('relaxed', 'RELAXED'), ('angry', 'ANGRY'), ('fearful', 'FEARFUL'), ('depressed', 'DEPRESSED'), ('lonely', 'LONELY'), ('surprised', 'SURPRISED'), ('annoyed', 'ANNOYED'), ('nervous', 'NERVOUS'), ('sick', 'SICK'), ('sleepy', 'SLEEPY'), ('excited', 'EXCITED'), ('stressed', 'STRESSED'), ('grumpy', 'GRUMPY'), ('scared', 'SCARED'), ('bored', 'BORED')], default='happy', max_length=136)),
                ('date', models.DateTimeField(null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.Customer')),
            ],
        ),
    ]
