# Generated by Django 3.0.3 on 2021-07-20 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='date',
        ),
        migrations.AddField(
            model_name='mood',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mood',
            name='type_of_mood',
            field=models.CharField(choices=[('happy', 'HAPPY'), ('sad', 'SAD'), ('anxious', 'ANXIOUS'), ('calm', 'CALM'), ('relaxed', 'RELAXED'), ('angry', 'ANGRY'), ('fearful', 'FEARFUL'), ('depressed', 'DEPRESSED'), ('lonely', 'LONELY'), ('surprised', 'SURPRISED'), ('annoyed', 'ANNOYED'), ('nervous', 'NERVOUS'), ('sick', 'SICK'), ('sleepy', 'SLEEPY'), ('excited', 'EXCITED'), ('stressed', 'STRESSED'), ('grumpy', 'GRUMPY'), ('scared', 'SCARED'), ('bored', 'BORED')], default='happy', max_length=200),
        ),
    ]
