# Generated by Django 3.0.3 on 2021-07-20 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20210720_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='type_of_mood',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('happy', 'HAPPY'), ('sad', 'SAD'), ('anxious', 'ANXIOUS'), ('calm', 'CALM'), ('relaxed', 'RELAXED'), ('angry', 'ANGRY'), ('fearful', 'FEARFUL'), ('depressed', 'DEPRESSED'), ('lonely', 'LONELY'), ('surprised', 'SURPRISED'), ('annoyed', 'ANNOYED'), ('nervous', 'NERVOUS'), ('sick', 'SICK'), ('sleepy', 'SLEEPY'), ('excited', 'EXCITED'), ('stressed', 'STRESSED'), ('grumpy', 'GRUMPY'), ('scared', 'SCARED'), ('bored', 'BORED')], default='happy', max_length=136),
        ),
    ]
