# Generated by Django 3.0.3 on 2021-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20210722_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='dateTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
