# Generated by Django 3.0.3 on 2021-07-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20210723_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
