# Generated by Django 3.0.3 on 2021-07-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20210724_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
