# Generated by Django 3.2.5 on 2021-07-31 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_diary_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Phone no. invalid. Please Don't enter +91/0 if u have.", regex='^[7-9]{1}[0-9]{9}$')]),
        ),
    ]
