# Generated by Django 3.2.5 on 2021-08-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hasPremium',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
